// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfkudYiMcKNDo_JDO7c1JN9Qo-y_-IfkU',
    appId: '1:60389078259:web:9c1f33a81fde18852f7386',
    messagingSenderId: '60389078259',
    projectId: 'expense-management-7fae6',
    authDomain: 'expense-management-7fae6.firebaseapp.com',
    storageBucket: 'expense-management-7fae6.firebasestorage.app',
    measurementId: 'G-3JJWJQMYTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAqkkNn2USxtUdA48wHNkjCdm-pa_T8M',
    appId: '1:60389078259:android:d6c58ff445794fa62f7386',
    messagingSenderId: '60389078259',
    projectId: 'expense-management-7fae6',
    storageBucket: 'expense-management-7fae6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Bq0py9LVjOUR2knS09tSX1vwGm_K7hw',
    appId: '1:60389078259:ios:9fa50b2e57a8de872f7386',
    messagingSenderId: '60389078259',
    projectId: 'expense-management-7fae6',
    storageBucket: 'expense-management-7fae6.firebasestorage.app',
    iosBundleId: 'com.example.expenseManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Bq0py9LVjOUR2knS09tSX1vwGm_K7hw',
    appId: '1:60389078259:ios:9fa50b2e57a8de872f7386',
    messagingSenderId: '60389078259',
    projectId: 'expense-management-7fae6',
    storageBucket: 'expense-management-7fae6.firebasestorage.app',
    iosBundleId: 'com.example.expenseManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfkudYiMcKNDo_JDO7c1JN9Qo-y_-IfkU',
    appId: '1:60389078259:web:e24a2b7f2bf6eeb62f7386',
    messagingSenderId: '60389078259',
    projectId: 'expense-management-7fae6',
    authDomain: 'expense-management-7fae6.firebaseapp.com',
    storageBucket: 'expense-management-7fae6.firebasestorage.app',
    measurementId: 'G-B66NMDJ42Q',
  );
}
